// svelte/src/components/RecipientsBadge.svelte
<script lang="ts">
  export let numTruncated: number
</script>

<span class="badge" data-testid="badge">
  +{numTruncated}
</span>

<style lang="scss">
  @use '../styles/variables';

  .badge {
    padding: 2px 5px;
    border-radius: 3px;
    background-color: variables.$color-primary;
    color: #f0f0f0;
  }
</style>

// react/src/components/RecipientsBadge.tsx
import styled from 'styled-components'
import type { ComponentPropsWithoutRef } from 'react'

export type RecipientsBadgeProps = {
  numTruncated: number
} & Omit<ComponentPropsWithoutRef<'span'>, 'className' | 'style'>

function RecipientsBadge({ numTruncated, ...rest }: RecipientsBadgeProps) {
  return (
    <span {...rest} data-testid="badge">
      +{numTruncated}
    </span>
  )
}

export default styled(RecipientsBadge)`
  flex-shrink: 0;
  padding: 2px 5px;
  border-radius: 3px;
  background-color: var(--color-primary);
  color: #f0f0f0;
  overflow: hidden;
`
